/*
Comment in JS : 
there are two types :
1) single line Comment
2) Multi Line Comment
*/

// var number1 = 12;
        // var number 1 = 12;  X
    // (_   $)
    // var $num1 = 12;
    // console.log($num1);
    // camelCase 
    // oddnumber     lower case 
    // ODDNUMBER     uper case 
    // odd_number    snake case 

    // oddNumber     camelCase  (must)

// -----------------------------------------------------

    // declaration  :
    // var a;
    // initialization :
    // a=12;
    // declaration + initialization : 
    // var a = 12;

// -----------------------------------------------------
//var vs let vs const : 

// var a = 12;
// // a = 100;
// var a = "Zafar";


// let b = 13;
// b=200;
// lt b = 2000; //X

// const c = 14;
// c = 300;  X
// const c = 13; //X

// console.log(a);
// console.log(b);
// console.log(c);


// Number , String ,boolean , Object(obj,Array,Null) ,undefined , BigInt


//debugging Console  
        //  zafar