/*
Comment in JS : 
there are two types :
1) single line Comment
2) Multi Line Comment
*/

// var number1 = 12;
        // var number 1 = 12;  X
    // (_   $)
    // var $num1 = 12;
    // console.log($num1);
    // camelCase 
    // oddnumber     lower case 
    // ODDNUMBER     uper case 
    // odd_number    snake case 

    // oddNumber     camelCase  (must)

// -----------------------------------------------------

    // declaration  :
    // var a;
    // initialization :
    // a=12;
    // declaration + initialization : 
    // var a = 12;

// -----------------------------------------------------
//var vs let vs const : 

// var a = 12;
// // a = 100;
// var a = "Zafar";


// let b = 13;
// b=200;
// lt b = 2000; //X

// const c = 14;
// c = 300;  X
// const c = 13; //X

// console.log(a);
// console.log(b);
// console.log(c);


// Number , String ,boolean , Object(obj,Array,Null) ,undefined , BigInt
// ---------------------------------------
// - String Indexing.    (-----)
// - Collection of char 
// - similer  to Array but not Same. 
//  indexing

// var str1 = "Zafar";
// var str2 = 'R';
// var str3 = `Techno`;

// console.log(str1, typeof str1);
// console.log(str2, typeof(str2));
// console.log(str3, typeof(str3));


// console.log("This is Multiple Line String");
// console.log(`This is 
// Multiple 
// Line 
// String`);


// var str1 = "Royal";
//          01234

// console.log(str1[4]);

// console.log(str1[str1.length-1]);



// str1.concat
// str1.indexOf
// str1.lastIndexOf
// str1.length
// str1.repeat
// str1.replace
// str1.replaceAll
// str1.toLowerCase
// str1.toUpperCase
/////////////////////////////////////
var str  = "Royal Technosoft pvt ltd";
console.log("Z",str,"Z");
// str1.trim
console.log("Z",str.trim(),"Z");
// str1.trimEnd //
console.log("Z",str.trimEnd(),"Z");
// str1.trimStart //
console.log("Z",str.trimStart(),"Z");

// str1.charAt
console.log(str.charAt(1));
// str1.charCodeAt  //
console.log(str.charCodeAt());   //ASCII Value



// str1.endsWith //
// str1.includes //
// str1.slice //
// str1.split//
// str1.startsWith //
// str1.substring //
// str1.substr  //








//debugging Console  
        //  zafar